routes/web.php
<?php
session_start();
ini_set('memory_limit', '-1');
use LinkedIn\Client;
use LinkedIn\Scope;
use LinkedIn\AccessToken;
use Carbon\Carbon;

Auth::loginUsingId(1);

Route::get('/linkedin', function(){
    // AQQlWxCXDY59DAISCNLC_9CgkRQY42fVyAN4qbbgwrCppJELO5TXw1WYtE3y8QDJ8WC3xRi6jO3chsCitNGwjTP_LXbpaVkep0-Mi503O62G3fsHSv8afnVpHGpAU6DXZ28jBGdyWcSbUXHD6UE6bWhNJBtzwTtW_x_S0qMstTBdB1JqZ9EPGnj11yNGIA
    // dd($_GET);
    $client = new Client(
        session('account')->username,
        session('account')->password
    );
    $client->setRedirectUrl('http://auto.localhost/linkedin');
    // retrieve access token using code provided by LinkedIn
    $accessToken = $client->getAccessToken($_GET['code']);    // $client->setRedirectUrl('http://your.domain.tld/path/to/script/');
    session(['accessToken' => json_encode($accessToken)]);
    $account = \App\Models\Account::find(session('account')->id);
    $account->token = json_decode(session('accessToken'))->token;
    $account->expire = json_decode(session('accessToken'))->expiresAt;
    $account->save();
    return back()->with('message', 'New token has been generated!');
});
Auth::routes();
/**
 * Pretty print whatever passed in
 *
 * @param mixed $anything
 */

// Auth access
Route::group(['middleware' => ['role:Admin','auth']], function(){
    Route::get('/', ['uses' => 'HomeController@index']);
    Route::get('/policy', function(){
        return view('policy');
    });
    
    Route::resource('/ad', 'AdController');
    Route::resource('/client', 'ClientController');
    Route::get('/import-data', ['uses' => 'ClientController@import', 'as' => 'client.import']);
    Route::post('/import-data', ['uses' => 'ClientController@import_store', 'as' => 'client.import.store']);

    Route::resource('/offer', 'OfferController');
    Route::get('/change-offer-status/{offer}', ['uses' => 'OfferController@change_status_get']);
    Route::patch('/change-offer-status/{offer}', ['uses' => 'OfferController@change_status_post', 'as' => 'offer.change']);
    Route::resource('/company', 'CompanyController');
    Route::resource('/course', 'CourseController');
    Route::resource('/trainer', 'TrainerController');
    Route::post('/get-trainers', ['uses' => 'TrainerController@getTrainersByCourse']);
    Route::resource('/social-media-account', 'AccountController');
    Route::resource('/payment', 'PaymentController');
    Route::resource('/bill', 'BillController');
    Route::resource('/user', 'UserController');
    Route::resource('/attachment', 'AttachmentController');

    // import excel files in ad
    Route::post('/extarct-emails', ['uses' => 'ImportController@import_emails_store']);
    Route::post('/extarct-phones', ['uses' => 'ImportController@import_phones_store']);

    Route::post('/post-trainers-to-course', ['uses' => 'OfferController@postTrainerToCourse']);

    Route::post('getAccountsByType', ['uses' => 'AccountController@getAccountsByType']);
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'clients';

    protected $guarded = ['id'];

    public function courses()
    {
        return $this->belongsToMany('App\Models\Client', 'courses_clients', 'course_id', 'client_id');
    }

    public function bills()
    {
        return $this->morphMany('App\Models\Bill', 'model', 'model');
    }

    // public function model()
    // {
    //     return $this->morphTo();
    // }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Models\Attachment;
use App\Models\CustomerType;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::latest()->get();

        return view('clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = CustomerType::pluck('name', 'id');

        return view('clients.create', compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            ['name' => 'required', 'phone' => 'required']
        );

        $client = Client::create($request->all());

        return redirect(route('client.index'))
                ->with('message', 'Your record has been saved successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Client  $Client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $Client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Client  $Client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Client  $Client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $this->validate($request, 
            ['title' => 'required', 'desription' => 'required']
        );

        $client->update($request->all());

        return redirect(route('client.index'))
                ->with('message', 'Your record has been updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Client  $Client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();

        return redirect(route('client.index'))
                ->with('message', 'Your record has been deleted successfully.');
    }

    public function import()
    {
        return view('clients.import');
    }

    public function import_store(Request $request)
    {
        if ($request->hasFile('excel_file'))
        {
            $request->excel_file->store('public');
            $attachment = Attachment::create(['name' => $request->excel_file->hashName(), 'orginal_name' => $request->excel_file->getClientOriginalName(), 'extention' => $request->excel_file->extension(), 'user_id' => auth()->user()->id]);
            \Excel::import(new \App\Imports\ClientImport, $request->excel_file->hashName(), 'public');
        }
        return redirect(route('client.index'))
                ->with('message', 'The excel file has been saved successfully.'); 
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')
@section('title')
    Create Client
@endsection

@section('content')

<!-- end page title --> 
{!! Form::open(['route' => 'client.store', 'method' => 'post']) !!}
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">

            <div class="form-group mb-3">
                {!! Form::label('Customer Type') !!}
                {!! Form::select('customer_type_id', $types, null, ['class' => 'select2 form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Name') !!}
                {!! Form::text('name', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Email') !!}
                {!! Form::text('email', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Phone') !!}
                {!! Form::text('phone', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Position') !!}
                {!! Form::text('position', null, ['class' => 'form-control']) !!}
            </div>


        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="col-12">
        <div class="text-center mb-3">
            <button type="submit" class="btn btn-success waves-effect waves-light">
                <span class="btn-label"><i class="mdi mdi-check-all"></i></span>Save
            </button>
        </div>
    </div> <!-- end col -->
</div>
{!! Form::close() !!}
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Advertisement
@endsection

@section('content')

<!-- end page title --> 
{!! Form::model($ad, ['route' => ['ad.update', $ad], 'method' => 'patch']) !!}
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">

            <div class="form-group mb-3">
                {!! Form::label('Title') !!}
                {!! Form::text('title', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Content') !!}
                {!! Form::textarea('desription', null, ['class' => 'form-control', 'rows' => 4]) !!}
            </div>

            <div class="form-group mb-3">
            @foreach($channels as $channel)
                <div class="checkbox checkbox-success form-check-inline">
                    {!! Form::checkbox('channels[]', $channel->id) !!}
                    <label>{{ $channel->name }}</label>
                </div>
            @endforeach
            </div>

        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="col-12">
        <div class="text-center mb-3">
            <button type="submit" class="btn btn-success waves-effect waves-light">
                <span class="btn-label"><i class="mdi mdi-check-all"></i></span>Save
            </button>
        </div>
    </div> <!-- end col -->
</div>
{!! Form::close() !!}
@endsection

resources/views/clients/import.blade.php
@extends('layouts.app')
@section('title')
    Import Clients from Excel
@endsection

@section('content')

<!-- end page title --> 
{!! Form::open(['route' => 'client.import.store', 'method' => 'post', 'files' => true]) !!}
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">
        <p>This tool enables you to import clients from existing excel file automatically.</p>
            <div class="form-group mb-3">
                {!! Form::label('Import excel file') !!}
                {!! Form::file('excel_file', ['class' => 'form-control']) !!}
            </div>

        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="col-12">
        <div class="text-center mb-3">
            <button type="submit" class="btn btn-success waves-effect waves-light">
                <span class="btn-label"><i class="mdi mdi-check-all"></i></span>Upload & Save
            </button>
        </div>
    </div> <!-- end col -->
</div>
{!! Form::close() !!}
@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')
@section('title')
    List Files
@endsection
@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <table id="basic-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Position</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if($clients->count() > 0)
                        @foreach($clients as $client)
                        <tr>
                            <td>{{ $client->name }}</td>
                            <td>{{ $client->phone }}</td>
                            <td>{{ $client->position }}</td>
                            <td>
                            <a href="{{ route('client.show', $client->id)}}" class="btn btn-xs btn-info"><i class="mdi mdi-eye"></i></a>
                            <a href="{{ route('client.edit', $client->id)}}" class="btn btn-xs btn-secondary"><i class="mdi mdi-pencil"></i></a>
                            <a href="#" class="btn btn-xs btn-danger" onclick="document.getElementById('deleteForm').submit();"><i class="mdi mdi-delete"></i></a>
                            {!! Form::open(['route' => ['client.destroy', $client], 'method' => 'delete', 'id' => 'deleteForm']) !!}
                            {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>
<!-- end row-->
                                        
@endsection

@section('script')
<script src="/assets/libs/datatables/jquery.dataTables.js"></script>
<script src="/assets/libs/datatables/dataTables.bootstrap4.js"></script>
<script src="/assets/libs/datatables/dataTables.buttons.min.js"></script>
<script src="/assets/libs/datatables/buttons.bootstrap4.min.js"></script>
<script src="/assets/libs/datatables/buttons.html5.min.js"></script>
<script src="/assets/js/pages/datatables.init.js"></script>
@endsection