routes/web.php
<?php
session_start();
ini_set('memory_limit', '-1');
use LinkedIn\Client;
use LinkedIn\Scope;
use LinkedIn\AccessToken;
use Carbon\Carbon;

Auth::loginUsingId(1);

Route::get('/linkedin', function(){
    // AQQlWxCXDY59DAISCNLC_9CgkRQY42fVyAN4qbbgwrCppJELO5TXw1WYtE3y8QDJ8WC3xRi6jO3chsCitNGwjTP_LXbpaVkep0-Mi503O62G3fsHSv8afnVpHGpAU6DXZ28jBGdyWcSbUXHD6UE6bWhNJBtzwTtW_x_S0qMstTBdB1JqZ9EPGnj11yNGIA
    // dd($_GET);
    $client = new Client(
        session('account')->username,
        session('account')->password
    );
    $client->setRedirectUrl('http://auto.localhost/linkedin');
    // retrieve access token using code provided by LinkedIn
    $accessToken = $client->getAccessToken($_GET['code']);    // $client->setRedirectUrl('http://your.domain.tld/path/to/script/');
    session(['accessToken' => json_encode($accessToken)]);
    $account = \App\Models\Account::find(session('account')->id);
    $account->token = json_decode(session('accessToken'))->token;
    $account->expire = json_decode(session('accessToken'))->expiresAt;
    $account->save();
    return back()->with('message', 'New token has been generated!');
});
Auth::routes();
/**
 * Pretty print whatever passed in
 *
 * @param mixed $anything
 */

// Auth access
Route::group(['middleware' => ['role:Admin','auth']], function(){
    Route::get('/', ['uses' => 'HomeController@index']);
    Route::get('/policy', function(){
        return view('policy');
    });
    
    Route::resource('/ad', 'AdController');
    Route::resource('/client', 'ClientController');
    Route::get('/import-data', ['uses' => 'ClientController@import', 'as' => 'client.import']);
    Route::post('/import-data', ['uses' => 'ClientController@import_store', 'as' => 'client.import.store']);

    Route::resource('/offer', 'OfferController');
    Route::get('/change-offer-status/{offer}', ['uses' => 'OfferController@change_status_get']);
    Route::patch('/change-offer-status/{offer}', ['uses' => 'OfferController@change_status_post', 'as' => 'offer.change']);
    Route::resource('/company', 'CompanyController');
    Route::resource('/course', 'CourseController');
    Route::resource('/trainer', 'TrainerController');
    Route::post('/get-trainers', ['uses' => 'TrainerController@getTrainersByCourse']);
    Route::resource('/social-media-account', 'AccountController');
    Route::resource('/payment', 'PaymentController');
    Route::resource('/bill', 'BillController');
    Route::resource('/user', 'UserController');
    Route::resource('/attachment', 'AttachmentController');

    // import excel files in ad
    Route::post('/extarct-emails', ['uses' => 'ImportController@import_emails_store']);
    Route::post('/extarct-phones', ['uses' => 'ImportController@import_phones_store']);

    Route::post('/post-trainers-to-course', ['uses' => 'OfferController@postTrainerToCourse']);

    Route::post('getAccountsByType', ['uses' => 'AccountController@getAccountsByType']);
});

app/Models/Attachment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Attachment extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'attachments';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'orginal_name', 'description', 'extention', 'model', 'model_id', 'user_id'];

    public function model()
    {
        return $this->morphTo();
    }

    public function trainer()
    {
        return $this->belongsTo('App\Models\Trainer');
    }

    public function resume()
    {
        return $this->belongsTo('App\Models\Resume');
    }

    public function ad()
    {
        return $this->belongsTo('App\Models\Ad');
    }

    public function bill()
    {
        return $this->belongsTo('App\Models\Bill');
    }
}

app/Http/Controllers/AttachmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Attachment;
use Illuminate\Http\Request;

class AttachmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $attachments = Attachment::where('model', null)->latest()->get();

        return view('attachments.index', compact('attachments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('attachments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // I'll make this attachment with no model.
        $this->validate($request, 
            ['name' => 'required']
        );

        if ($request->hasFile('attach'))
        {
            $request->attach->store('attachments');
            $attachment = Attachment::create(['name' => $request->attach->hashName(), 'orginal_name' => $request->attach->getClientOriginalName(), 'extention' => $request->attach->extension(), 'user_id' => auth()->user()->id]);
        }

        return redirect(route('attachment.index'))
                ->with('message', 'Your record has been saved successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Client  $Client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $Client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Client  $Client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Client  $Client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $this->validate($request, 
            ['title' => 'required', 'desription' => 'required']
        );

        $client->update($request->all());

        return redirect(route('client.index'))
                ->with('message', 'Your record has been updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Client  $Client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();

        return redirect(route('client.index'))
                ->with('message', 'Your record has been deleted successfully.');
    }

    public function import()
    {
        return view('clients.import');
    }

    public function import_store(Request $request)
    {
        if ($request->hasFile('excel_file'))
        {
            $request->excel_file->store('public');
            $attachment = Attachment::create(['name' => $request->excel_file->hashName(), 'orginal_name' => $request->excel_file->getClientOriginalName(), 'extention' => $request->excel_file->extension(), 'user_id' => auth()->user()->id]);
            \Excel::import(new \App\Imports\ClientImport, $request->excel_file->hashName(), 'public');
        }
        return redirect(route('client.index'))
                ->with('message', 'The excel file has been saved successfully.'); 
    }
}

resources/views/attachments/create.blade.php
@extends('layouts.app')
@section('title')
    Upload File
@endsection

@section('content')

<!-- end page title --> 
{!! Form::open(['route' => 'attachment.store', 'method' => 'post', 'files' => true]) !!}
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">

            <div class="form-group mb-3">
                {!! Form::label('Name') !!}
                {!! Form::text('name', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('File') !!}
                {!! Form::file('attach', ['class' => 'form-control']) !!}
            </div>

        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="col-12">
        <div class="text-center mb-3">
            <button type="submit" class="btn btn-success waves-effect waves-light">
                <span class="btn-label"><i class="mdi mdi-check-all"></i></span>Save
            </button>
        </div>
    </div> <!-- end col -->
</div>
{!! Form::close() !!}
@endsection

resources/views/attachments/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Advertisement
@endsection

@section('content')

<!-- end page title --> 
{!! Form::model($ad, ['route' => ['ad.update', $ad], 'method' => 'patch']) !!}
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">

            <div class="form-group mb-3">
                {!! Form::label('Title') !!}
                {!! Form::text('title', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Content') !!}
                {!! Form::textarea('desription', null, ['class' => 'form-control', 'rows' => 4]) !!}
            </div>

            <div class="form-group mb-3">
            @foreach($channels as $channel)
                <div class="checkbox checkbox-success form-check-inline">
                    {!! Form::checkbox('channels[]', $channel->id) !!}
                    <label>{{ $channel->name }}</label>
                </div>
            @endforeach
            </div>

        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="col-12">
        <div class="text-center mb-3">
            <button type="submit" class="btn btn-success waves-effect waves-light">
                <span class="btn-label"><i class="mdi mdi-check-all"></i></span>Save
            </button>
        </div>
    </div> <!-- end col -->
</div>
{!! Form::close() !!}
@endsection

resources/views/attachments/index.blade.php
@extends('layouts.app')
@section('title')
    List attachments
@endsection
@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <table id="basic-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if($attachments->count() > 0)
                        @foreach($attachments as $attachment)
                        <tr>
                            <td>{{ $attachment->orginal_name }}</td>
                            <td>{{ $attachment->description }}</td>
                            <td>
                            <a href="{{ route('attachment.show', $attachment->id)}}" class="btn btn-xs btn-info"><i class="mdi mdi-eye"></i></a>
                            <a href="{{ route('attachment.edit', $attachment->id)}}" class="btn btn-xs btn-secondary"><i class="mdi mdi-pencil"></i></a>
                            <a href="#" class="btn btn-xs btn-danger" onclick="document.getElementById('deleteForm').submit();"><i class="mdi mdi-delete"></i></a>
                            {!! Form::open(['route' => ['attachment.destroy', $attachment], 'method' => 'delete', 'id' => 'deleteForm']) !!}
                            {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>
<!-- end row-->
                                        
@endsection

@section('script')
<script src="/assets/libs/datatables/jquery.dataTables.js"></script>
<script src="/assets/libs/datatables/dataTables.bootstrap4.js"></script>
<script src="/assets/libs/datatables/dataTables.buttons.min.js"></script>
<script src="/assets/libs/datatables/buttons.bootstrap4.min.js"></script>
<script src="/assets/libs/datatables/buttons.html5.min.js"></script>
<script src="/assets/js/pages/datatables.init.js"></script>
@endsection