routes/web.php
<?php
session_start();
ini_set('memory_limit', '-1');
use LinkedIn\Client;
use LinkedIn\Scope;
use LinkedIn\AccessToken;
use Carbon\Carbon;

Auth::loginUsingId(1);

Route::get('/linkedin', function(){
    // AQQlWxCXDY59DAISCNLC_9CgkRQY42fVyAN4qbbgwrCppJELO5TXw1WYtE3y8QDJ8WC3xRi6jO3chsCitNGwjTP_LXbpaVkep0-Mi503O62G3fsHSv8afnVpHGpAU6DXZ28jBGdyWcSbUXHD6UE6bWhNJBtzwTtW_x_S0qMstTBdB1JqZ9EPGnj11yNGIA
    // dd($_GET);
    $client = new Client(
        session('account')->username,
        session('account')->password
    );
    $client->setRedirectUrl('http://auto.localhost/linkedin');
    // retrieve access token using code provided by LinkedIn
    $accessToken = $client->getAccessToken($_GET['code']);    // $client->setRedirectUrl('http://your.domain.tld/path/to/script/');
    session(['accessToken' => json_encode($accessToken)]);
    $account = \App\Models\Account::find(session('account')->id);
    $account->token = json_decode(session('accessToken'))->token;
    $account->expire = json_decode(session('accessToken'))->expiresAt;
    $account->save();
    return back()->with('message', 'New token has been generated!');
});
Auth::routes();
/**
 * Pretty print whatever passed in
 *
 * @param mixed $anything
 */

// Auth access
Route::group(['middleware' => ['role:Admin','auth']], function(){
    Route::get('/', ['uses' => 'HomeController@index']);
    Route::get('/policy', function(){
        return view('policy');
    });
    
    Route::resource('/ad', 'AdController');
    Route::resource('/client', 'ClientController');
    Route::get('/import-data', ['uses' => 'ClientController@import', 'as' => 'client.import']);
    Route::post('/import-data', ['uses' => 'ClientController@import_store', 'as' => 'client.import.store']);

    Route::resource('/offer', 'OfferController');
    Route::get('/change-offer-status/{offer}', ['uses' => 'OfferController@change_status_get']);
    Route::patch('/change-offer-status/{offer}', ['uses' => 'OfferController@change_status_post', 'as' => 'offer.change']);
    Route::resource('/company', 'CompanyController');
    Route::resource('/course', 'CourseController');
    Route::resource('/trainer', 'TrainerController');
    Route::post('/get-trainers', ['uses' => 'TrainerController@getTrainersByCourse']);
    Route::resource('/social-media-account', 'AccountController');
    Route::resource('/payment', 'PaymentController');
    Route::resource('/bill', 'BillController');
    Route::resource('/user', 'UserController');
    Route::resource('/attachment', 'AttachmentController');

    // import excel files in ad
    Route::post('/extarct-emails', ['uses' => 'ImportController@import_emails_store']);
    Route::post('/extarct-phones', ['uses' => 'ImportController@import_phones_store']);

    Route::post('/post-trainers-to-course', ['uses' => 'OfferController@postTrainerToCourse']);

    Route::post('getAccountsByType', ['uses' => 'AccountController@getAccountsByType']);
});

app/Models/Bill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Bill extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'bills';

    protected $guarded = ['id'];

    // public function model()
    // {
    //     return $this->morphTo();
    // }
    
    public function offer()
    {
        return $this->belongsTo('App\Models\Offer');
    }

    public function type()
    {
        return $this->belongsTo('App\Models\BillType', 'bill_type_id');
    }

    public function clients()
    {
        return $this->morphMany('App\Models\Client', 'model', 'model');
    }

    public function companies()
    {
        return $this->morphMany('App\Models\Company', 'model', 'model');
    }
}

app/Models/BillType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BillType extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'bill_types';

    protected $guarded = ['id'];

    public function bills()
    {
        return $this->hasMany('App\Models\Bill');
    }
}

app/Http/Controllers/BillController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bill;
use App\Models\BillType;
use App\Models\Client;
use App\Models\Offer;
use App\Models\Company;
use Illuminate\Http\Request;
use Carbon\Carbon;
class BillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bills = Bill::latest()->get();

        return view('bills.index', compact('bills'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = BillType::pluck('name', 'id');
        $clients = Client::pluck('name', 'id');
        $companies = Company::pluck('name', 'id');
        $offers = Offer::latest()->pluck('title', 'id');

        return view('bills.create', compact('types', 'clients', 'companies', 'offers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->validate($request, 
        //     ['title' => 'required', 'description' => 'required']
        // );
        $lastBillNumber = Bill::latest()->first()->bill_number;

        $bill = Bill::create(array_merge($request->except('client_id', 'company_id'),
         ['bill_number' => $lastBillNumber + 1, 'date' => Carbon::now()]));
        
         if($request->bill_type_id == 1)
        {
            $company = Company::find($request->company_id);
            $bill->update(['model' => 'App\Models\Company', 'model_id' => $company->id]);
            // $bill->companies()->save($company);
        }

        if($request->bill_type_id == 2)
        {
            $client = Client::find($request->client_id);
            $client->bills()->save($bill);
        }
        
        
        return redirect(route('bill.index'))
                ->with('message', 'Your record has been saved successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Bill  $ad
     * @return \Illuminate\Http\Response
     */
    public function show(Bill $ad)
    {
        return view('bills.show', compact('ad'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Bill  $ad
     * @return \Illuminate\Http\Response
     */
    public function edit(Bill $ad)
    {
        $channels = BillChannel::get();

        return view('bills.edit', compact('ad', 'channels'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Bill  $ad
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bill $ad)
    {
        $this->validate($request, 
            ['title' => 'required', 'desription' => 'required']
        );

        $ad->update($request->only('title', 'desription'));
        $ad->channels()->sync($request->channels);

        return redirect(route('ad.index'))
                ->with('message', 'Your record has been updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Bill  $ad
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bill $ad)
    {
        $ad->delete();

        return redirect(route('ad.index'))
                ->with('message', 'Your record has been deleted successfully.');
    }
}

resources/views/bills/create.blade.php
@extends('layouts.app')
@section('title')
    Create Bill
@endsection

@section('content')

<!-- end page title --> 
{!! Form::open(['route' => 'bill.store', 'method' => 'post']) !!}
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">

            <div class="form-group mb-3">
                {!! Form::label('Bill Type') !!}
                {!! Form::select('bill_type_id', $types, null, ['class' => 'select2 form-control', 'id' => 'bill_type']) !!}
            </div>

            <div class="form-group mb-3" id="offer">
                {!! Form::label('Offer') !!}
                {!! Form::select('offer_id', $offers, null, ['class' => 'select2 form-control']) !!}
            </div>

            <div class="form-group mb-3" id="client">
                {!! Form::label('Client') !!}
                {!! Form::select('client_id', $clients, null, ['class' => 'select2 form-control']) !!}
            </div>

            <!-- <div class="form-group mb-3" id="company">
                {!! Form::label('Company') !!}
                {!! Form::select('company_id', $companies, null, ['class' => 'select2 form-control']) !!}
            </div> -->

        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="page-title-box">
        <h4 class="page-title">Payment Details</h4>
    </div>

    <div class="col-lg-12">
        <div class="card-box">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group mb-3">
                        {!! Form::label('Total Amount') !!}
                        {!! Form::text('total', null, ['class' => 'form-control', 'id' => 'total']) !!}
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group mb-3">
                        {!! Form::label('Paid Amount') !!}
                        {!! Form::text('paid_amount', null, ['class' => 'form-control', 'id' => 'paid_amount']) !!}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group mb-3">
                        {!! Form::label('Remaining Amount') !!}
                        {!! Form::text('remaining_amount', null, ['class' => 'form-control', 'id' => 'remaining_amount']) !!}
                    </div>
                </div>
        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="col-12">
        <div class="text-center mb-3">
            <button type="submit" class="btn btn-success waves-effect waves-light">
                <span class="btn-label"><i class="mdi mdi-check-all"></i></span>Save & export as pdf
            </button>
        </div>
    </div> <!-- end col -->
</div>
{!! Form::close() !!}
@endsection

@section('script')
<script>
$(document).ready(function() {
    $('#client').hide();
    $('#company').show();
});

$('#bill_type').on('change', function() {
    if($(this).val() == 1)
    {
        $('#company').show();
        $('#offer').show();
        $('#client').hide();
    }

    if($(this).val() == 2)
    {
        $('#company').hide();
        $('#offer').hide();
        $('#client').show();
    }
});
</script>
@endsection

resources/views/bills/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Advertisement
@endsection

@section('content')

<!-- end page title --> 
{!! Form::model($ad, ['route' => ['ad.update', $ad], 'method' => 'patch']) !!}
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">

            <div class="form-group mb-3">
                {!! Form::label('Title') !!}
                {!! Form::text('title', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Content') !!}
                {!! Form::textarea('desription', null, ['class' => 'form-control', 'rows' => 4]) !!}
            </div>

            <div class="form-group mb-3">
            @foreach($channels as $channel)
                <div class="checkbox checkbox-success form-check-inline">
                    {!! Form::checkbox('channels[]', $channel->id) !!}
                    <label>{{ $channel->name }}</label>
                </div>
            @endforeach
            </div>

        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="col-12">
        <div class="text-center mb-3">
            <button type="submit" class="btn btn-success waves-effect waves-light">
                <span class="btn-label"><i class="mdi mdi-check-all"></i></span>Save
            </button>
        </div>
    </div> <!-- end col -->
</div>
{!! Form::close() !!}
@endsection

resources/views/bills/index.blade.php
@extends('layouts.app')
@section('title')
    List Bills
@endsection
@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <table id="basic-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>Bill Number</th>
                            <th>Customer</th>
                            <th>Course</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if($bills->count() > 0)
                        @foreach($bills as $bill)
                        <tr>
                            <td>{{ $bill->bill_number }}</td>
                            <td>
                            @if($bill->model == 'App\Models\Company')
                                {{ \App\Models\Company::find($bill->model_id)->name }}
                            @elseif($bill->model == 'App\Models\Client')
                                {{ \App\Models\Client::find($bill->model_id)->name }}
                            @endif
                            </td>
                            <td>
                            @foreach($bill->offer->courses as $course)
                                {{ $course->title .', ' }}
                            @endforeach
                            </td>
                            <td>
                            <a href="{{ route('bill.show', $bill->id)}}" class="btn btn-xs btn-info"><i class="mdi mdi-eye"></i></a>
                            <a href="{{ route('bill.edit', $bill->id)}}" class="btn btn-xs btn-secondary"><i class="mdi mdi-pencil"></i></a>
                            <a href="#" class="btn btn-xs btn-danger" onclick="document.getElementById('deleteForm').submit();"><i class="mdi mdi-delete"></i></a>
                            {!! Form::open(['route' => ['bill.destroy', $bill], 'method' => 'delete', 'id' => 'deleteForm']) !!}
                            {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>
<!-- end row-->
                                        
@endsection

@section('script')
<script src="/assets/libs/datatables/jquery.dataTables.js"></script>
<script src="/assets/libs/datatables/dataTables.bootstrap4.js"></script>
<script src="/assets/libs/datatables/dataTables.buttons.min.js"></script>
<script src="/assets/libs/datatables/buttons.bootstrap4.min.js"></script>
<script src="/assets/libs/datatables/buttons.html5.min.js"></script>
<script src="/assets/js/pages/datatables.init.js"></script>
@endsection