routes/web.php
<?php
session_start();
ini_set('memory_limit', '-1');
use LinkedIn\Client;
use LinkedIn\Scope;
use LinkedIn\AccessToken;
use Carbon\Carbon;

Auth::loginUsingId(1);

Route::get('/linkedin', function(){
    // AQQlWxCXDY59DAISCNLC_9CgkRQY42fVyAN4qbbgwrCppJELO5TXw1WYtE3y8QDJ8WC3xRi6jO3chsCitNGwjTP_LXbpaVkep0-Mi503O62G3fsHSv8afnVpHGpAU6DXZ28jBGdyWcSbUXHD6UE6bWhNJBtzwTtW_x_S0qMstTBdB1JqZ9EPGnj11yNGIA
    // dd($_GET);
    $client = new Client(
        session('account')->username,
        session('account')->password
    );
    $client->setRedirectUrl('http://auto.localhost/linkedin');
    // retrieve access token using code provided by LinkedIn
    $accessToken = $client->getAccessToken($_GET['code']);    // $client->setRedirectUrl('http://your.domain.tld/path/to/script/');
    session(['accessToken' => json_encode($accessToken)]);
    $account = \App\Models\Account::find(session('account')->id);
    $account->token = json_decode(session('accessToken'))->token;
    $account->expire = json_decode(session('accessToken'))->expiresAt;
    $account->save();
    return back()->with('message', 'New token has been generated!');
});
Auth::routes();
/**
 * Pretty print whatever passed in
 *
 * @param mixed $anything
 */

// Auth access
Route::group(['middleware' => ['role:Admin','auth']], function(){
    Route::get('/', ['uses' => 'HomeController@index']);
    Route::get('/policy', function(){
        return view('policy');
    });
    
    Route::resource('/ad', 'AdController');
    Route::resource('/client', 'ClientController');
    Route::get('/import-data', ['uses' => 'ClientController@import', 'as' => 'client.import']);
    Route::post('/import-data', ['uses' => 'ClientController@import_store', 'as' => 'client.import.store']);

    Route::resource('/offer', 'OfferController');
    Route::get('/change-offer-status/{offer}', ['uses' => 'OfferController@change_status_get']);
    Route::patch('/change-offer-status/{offer}', ['uses' => 'OfferController@change_status_post', 'as' => 'offer.change']);
    Route::resource('/company', 'CompanyController');
    Route::resource('/course', 'CourseController');
    Route::resource('/trainer', 'TrainerController');
    Route::post('/get-trainers', ['uses' => 'TrainerController@getTrainersByCourse']);
    Route::resource('/social-media-account', 'AccountController');
    Route::resource('/payment', 'PaymentController');
    Route::resource('/bill', 'BillController');
    Route::resource('/user', 'UserController');
    Route::resource('/attachment', 'AttachmentController');

    // import excel files in ad
    Route::post('/extarct-emails', ['uses' => 'ImportController@import_emails_store']);
    Route::post('/extarct-phones', ['uses' => 'ImportController@import_phones_store']);

    Route::post('/post-trainers-to-course', ['uses' => 'OfferController@postTrainerToCourse']);

    Route::post('getAccountsByType', ['uses' => 'AccountController@getAccountsByType']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    protected $guard_name = 'web';
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::latest()->get();

        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('name', 'id');

        return view('user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            ['name' => 'required', 'email' => 'required', 'password' => 'required']
        );
        $user = User::create($request->only('name', 'email', 'password'));
        $user->assignRole($request->role_id);

        return redirect(route('user.index'))
                ->with('message', 'Your record has been saved successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('title')
    Create User
@endsection

@section('content')

<!-- end page title --> 
{!! Form::open(['route' => 'user.store', 'method' => 'post']) !!}
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">

            <div class="form-group mb-3">
                {!! Form::label('Role') !!}
                {!! Form::select('role_id', $roles, null, ['class' => 'select2 form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Name') !!}
                {!! Form::text('name', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Email') !!}
                {!! Form::text('email', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Password') !!}
                {!! Form::password('password', ['class' => 'form-control']) !!}
            </div>

        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="col-12">
        <div class="text-center mb-3">
            <button type="submit" class="btn btn-success waves-effect waves-light">
                <span class="btn-label"><i class="mdi mdi-check-all"></i></span>Save
            </button>
        </div>
    </div> <!-- end col -->
</div>
{!! Form::close() !!}
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Advertisement
@endsection

@section('content')

<!-- end page title --> 
{!! Form::model($ad, ['route' => ['ad.update', $ad], 'method' => 'patch']) !!}
<div class="row">
    <div class="col-lg-12">
        <div class="card-box">

            <div class="form-group mb-3">
                {!! Form::label('Title') !!}
                {!! Form::text('title', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group mb-3">
                {!! Form::label('Content') !!}
                {!! Form::textarea('desription', null, ['class' => 'form-control', 'rows' => 4]) !!}
            </div>

            <div class="form-group mb-3">
            @foreach($channels as $channel)
                <div class="checkbox checkbox-success form-check-inline">
                    {!! Form::checkbox('channels[]', $channel->id) !!}
                    <label>{{ $channel->name }}</label>
                </div>
            @endforeach
            </div>

        </div> <!-- end card-box -->
    </div> <!-- end col -->
</div>

<div class="row">
    <div class="col-12">
        <div class="text-center mb-3">
            <button type="submit" class="btn btn-success waves-effect waves-light">
                <span class="btn-label"><i class="mdi mdi-check-all"></i></span>Save
            </button>
        </div>
    </div> <!-- end col -->
</div>
{!! Form::close() !!}
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('title')
    List Users
@endsection
@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <table id="basic-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if($users->count() > 0)
                        @foreach($users as $user)
                        <tr>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->roles->first() != null ? $user->roles->first()->name : '' }}</td>
                            <td>
                            <a href="{{ route('user.show', $user->id)}}" class="btn btn-xs btn-info"><i class="mdi mdi-eye"></i></a>
                            <a href="{{ route('user.edit', $user->id)}}" class="btn btn-xs btn-secondary"><i class="mdi mdi-pencil"></i></a>
                            <a href="#" class="btn btn-xs btn-danger" onclick="document.getElementById('deleteForm').submit();"><i class="mdi mdi-delete"></i></a>
                            {!! Form::open(['route' => ['user.destroy', $user], 'method' => 'delete', 'id' => 'deleteForm']) !!}
                            {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>
<!-- end row-->
                                        
@endsection

@section('script')
<script src="/assets/libs/datatables/jquery.dataTables.js"></script>
<script src="/assets/libs/datatables/dataTables.bootstrap4.js"></script>
<script src="/assets/libs/datatables/dataTables.buttons.min.js"></script>
<script src="/assets/libs/datatables/buttons.bootstrap4.min.js"></script>
<script src="/assets/libs/datatables/buttons.html5.min.js"></script>
<script src="/assets/js/pages/datatables.init.js"></script>
@endsection